services:
  prometheus:
    image: prom/prometheus:latest
    container_name: url-redir-prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - url-redir-net

  loki:
    image: grafana/loki:latest
    container_name: url-redir-loki
    volumes:
      - ./infra/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - url-redir-net

  promtail:
    image: grafana/promtail:latest
    container_name: url-redir-promtail
    volumes:
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infra/promtail/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - url-redir-net

  grafana:
    image: grafana/grafana:latest
    container_name: url-redir-grafana
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/grafana/provisioning/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3004:3000"
    depends_on:
      - prometheus
      - loki
    networks:
      - url-redir-net

volumes:
  prometheus_data:
  grafana_data:

networks:
  url-redir-net:
    external: true
    name: url-redir-short_url-redir-net
